name: 'Pull Request'

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy-pr:
    name: Deploy PR
    runs-on: ubuntu-latest
    environment: dev
    env:
      PROJECT: vajeh-auth
      WORKSPACE: pr-${{ github.event.pull_request.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install invoke
        run: pip install invoke

      - name: Deploy PR - init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: invoke init

      - name: Deploy PR - apply
        uses: nick-fields/retry@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          timeout_minutes: 10
          max_attempts: 2
          command: invoke apply
